name: Go push main

on: 
  push:
    branches: [ main ]

permissions: read-all

jobs:
  #TODO: support multiple config files.
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
    with:
      go-version: 1.17

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'failure')
    steps:
      - run: |

        #TODO: create issue on the repo about the failure.
        echo "it failed"
        exit 1

  verify-provenance:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |

        #TODO: slsa-verifier for all existing releases, and create issue if failure.
        echo "it worked"

  verify-assets:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |

        #TODO: verify no assest were created.
        echo "it worked"