
name: Go Pre submits ldflags - E2e tests
on: 
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  args:
    if: needs.shim.outputs.continue == 'yes' && github.event_name == 'push' && github.ref_type == 'tag'
    outputs:
      version: ${{ steps.ldflags.outputs.version }}
      commit: ${{ steps.ldflags.outputs.commit }}
      branch: ${{ steps.ldflags.outputs.branch }}
    steps:
      - id: ldflags
        run: |
          set -euo pipefail
          
          BRANCH=$(echo "$THIS_FILE" | cut -d '.' -f4)
          echo "::set-output name=version::-X main.gitVersion=v1.2.3"
          echo "::set-output name=commit::-X main.gitCommit=abcdef"
          echo "::set-output name=branch::-X main.gitBranch=$BRANCH"
  build:
    needs: [args]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: ./.github/workflows/slsa3_builder.yml
    with:
      go-version: 1.18
      config-file: .github/configs-go/config-ldflags.yml
      evaluated-envs: "VERSION:${{needs.args.outputs.version}},COMMIT:${{needs.args.outputs.commit}},BRANCH:${{needs.args.outputs.branch}}"

  verify-provenance:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          #TODO: verify the non-signed provenance content.
          echo "it worked"
  