name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.3.4

      - name: setup-go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.17'

      - name: Run tests for builder
        run: |
          set -euo pipefail

          # Download dependencies.
          go mod vendor
          # Build.
          go build -mod=vendor
          # Test.
          go test -mod=vendor -v ./...
